Algoritmo "A10Q3"

Var
   idade: vetor [1..10] de inteiro
   i: inteiro
Inicio
      para i de 1 ate 10 faca
      escreva("Informe a idade da",i,"ª pessoa:")
      leia(idade[i])
      escreval("--------------------------------")
      fimpara
      escreval
      escreval("A idade informada da PRIMEIRA pessoa é:",idade[1])
      escreval("A idade informada da ULTIMA pessoa é:",idade[10])
      
Fimalgoritmo