Algoritmo "questão12"
Var
   valorA: real
   valorB: real
   aTrocado: real
   bTrocado: real
Inicio
      escreva("Digite o valor de A:")
      leia(valorA)
      escreva("Digite o valor de B:")
      leia(valorB)
      aTrocado <- valorB
      bTrocado <- valorA
      escreval("Você informou os valores:")
      escreval("A=",valorA)
      escreval("B=",valorB)
      escreval("")
      escreval("Os valores agora são:")
      escreval("A=",aTrocado)
      escreval("B=",bTrocado)
Fimalgoritmo