Algoritmo "questão7"

Var
   cotacaoDolar, reais, umDolar, umReal, totalDolar: real
Inicio
   escreva("Informe a cotação do Dólar hoje: R$")
   leia(cotacaoDolar)
   escreva("Agora informe um valor em Reais: R$")
   leia(reais)
   umReal <- 1.00
   umDolar <- umReal * cotacaodolar
   totalDolar <- reais * umDolar
   escreva("o valor de R$",reais," , é o equivalente a:",totalDolar,"USD")
Fimalgoritmo