Algoritmo "semnome"

Var
   // Seção de Declarações das variáveis
   numeroA: inteiro
   numeroB: inteiro
   resultado: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("informe um número inteiro:")
   leia(numeroA)
   escreva("informe outro número inteiro:")
   leia(numeroB)
   resultado <- numeroA \ numeroB
   escreva ("O resultado é:",resultado)
Fimalgoritmo