Algoritmo "a5Q4"
Var
   numUm: real
   numDois: real
Inicio
   escreval("Informe o primeiro número:")
   leia(numUm)
   escreval("informe o segundo número:")
   leia(numDois)
   se numUm = numDois entao
      escreval("Os números informados são IGUAIS!")
   fimse
   se numUm > numDois entao
      escreval("O PRIMEIRO número (",numUm," ) é o MAIOR!")
   fimse
   se numUm < numDois entao
   escreval("O SEGUNDO múmero (",numDois," ) é o MAIOR!")
   fimse

Fimalgoritmo